name: Notify Packagist

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Packagist of update
        run: |
          curl -XPOST -H 'content-type:application/json' \
            'https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_API_TOKEN }}' \
            -d '{"repository":{"url":"https://github.com/zamasoftnet/cti.php"}}'
